.TH _printf
.SH NAME
_printf \ print formatted output to stdout
.SH SYNOPSIS
.B #include\ "main.h"
.P
.B _printf
Format [Argument]
.SH COMPILE
gcc -Wall -Werror -Wextra -pedantic -std=gnu89 -Wno-format *.c
.SH DESCRIPTION
int _printf(const char *format,...);
.TP
In this home made version _printf is behaving like printf from the standard library.
.RE
The function prints output to stdout(standard output) in the order the arguments are given.
In case of format specifiers, see below the options:
.TP
\fB%c
print single character
.TP
\fB%s
print string
.TP
\fB%
print percentage sign
.TP
\fB%i
print integer number
.TP
\fB%d
print decimal numbers
.SH RETURN
Returns number of times printed
.SH BUGS
no bugs detected yet
.SH AUTHORS
Walter Carrion and Nadja Miranda
